##
## EPITECH PROJECT, 2024
## chocolatine_test
## File description:
## chocolatine.yml
##

name: petit pain

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  MAIN_REPO: "EpitechPGEPromo2029/B-DOP-200-LIL-2-1-chocolatine-arthur.vignes"
  MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-LIL-2-1-chocolatine-arthur.vignes.git"
  EXECUTABLES: "my_program"

jobs:
  push_to_mirror:
    name: Mirror Repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}