name: Chocolatine Workflow

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_coding_style:
    name: Check Coding Style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run coding style checker
        id: coding_style
        shell: bash
        run: |
          echo "Running coding style check..."
          check.sh $(pwd) $(pwd) || true
          
          if [ -f coding-style-reports.log ]; then
            echo "Found coding style violations:"
            cat coding-style-reports.log
            
            # Create GitHub annotations for each error
            while IFS= read -r line; do
              if [[ $line =~ ^([^:]+):([0-9]+): ]]; then
                file="${BASH_REMATCH[1]}"
                line_num="${BASH_REMATCH[2]}"
                echo "::error file=$file,line=$line_num::$line"
              fi
            done < coding-style-reports.log
            
            echo "❌ Coding style violations found"
            exit 1
          else
            echo "✅ No coding style violations found"
          fi

  build:
    name: Build Project
    needs: check_coding_style
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          make
          echo "Build successful"

      - name: Clean build
        run: |
          make clean
          echo "Clean completed"

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute tests
        run: |
          make tests_run
          echo "Tests completed"

  push_to_mirror:
    name: Push to Mirror
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
