##
## EPITECH PROJECT, 2025
## chocolatine_test
## File description:
## chocolatine.yml
##

name: petit pain

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  MIRROR_URL: "git@github.com:4rthurV/chocolatine_mirror.git"
  EXECUTABLES: "my_program"

jobs:
  check_repo:
    name: Check branch validity
    if: github.repository != 'git@github.com:4rthurV/chocolatine_mirror.git'
    runs-on: ubuntu-latest
    outputs:
      branch_valid: ${{ !startsWith(github.ref, 'refs/heads/ga-ignore-') }}
    steps:
      - name: Verify branch
        id: branch_check
        run: |
          if [[ "${{ github.ref }}" == refs/heads/ga-ignore-* ]]; then
            echo "Branch is ignored (ga-ignore-*)"
            echo "branch_valid=false" >> $GITHUB_OUTPUT
          else
            echo "Branch is valid"
            echo "branch_valid=true" >> $GITHUB_OUTPUT
          fi

  check_coding_style:
    name: coding style checker
    needs: [check_repo]
    if: github.repository != 'git@github.com:4rthurV/chocolatine_mirror.git'
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    outputs:
      run_rest_jobs: ${{ steps.set_output.outputs.run_jobs }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: run coding style
        shell: bash
        run: check.sh $(pwd) $(pwd) || true

      - name: check style error
        id: set_output
        shell: bash
        run: |
          if [ -s $(pwd)/coding-style-reports.log ]; then
            echo "run_jobs=false" >> $GITHUB_OUTPUT
            while IFS=':' read -r FILE LINE GRAVITY ERROR; do
              echo "::error file=$FILE,line=$LINE,title=$GRAVITY::$ERROR"
            done < $(pwd)/coding-style-reports.log
          else
            echo "run_jobs=true" >> $GITHUB_OUTPUT
          fi

  check_program_compilation:
    name: Checking compilation
    needs: [check_coding_style]
    if: github.repository != 'git@github.com:4rthurV/chocolatine_mirror.git' && needs.check_coding_style.outputs.run_rest_jobs == 'true'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    outputs:
      run_rest_jobs: ${{ steps.set_output.outputs.run_jobs }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: run make
        timeout-minutes: 2
        run: make

      - name: check files existence
        id: set_output
        run: |
          if [ -f "${{ env.EXECUTABLES }}" ]; then
            echo "run_jobs=true" >> $GITHUB_OUTPUT
          else
            echo "run_jobs=false" >> $GITHUB_OUTPUT
            echo "::error:: compilation failed"
            exit 1
          fi

      - name: Clean build
        run: make clean

  run_tests:
    name: Run Tests
    needs: [check_program_compilation]
    if: github.repository != 'git@github.com:4rthurV/chocolatine_mirror.git' && needs.check_program_compilation.outputs.run_rest_jobs == 'true'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run tests
        timeout-minutes: 2
        run: make tests_run

  push_to_mirror:
    name: mirror repository
    needs: [run_tests]
    if: github.repository != 'git@github.com:4rthurV/chocolatine_mirror.git' && github.event_name == 'push' && needs.check_program_compilation.outputs.run_rest_jobs == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
