##
## EPITECH PROJECT, 2024
## B-DOP-200-LIL-2-1-chocolatine-arthur.vignes
## File description:
## chocolatine.yml
##

name: petit pain

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

env:
  MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-LIL-2-1-chocolatine-arthur.vignes"
  EXECUTABLES: "my_program"
#  LIBRARIES: "lib/libmy.a"

jobs:
  check_branch:
    name: Check branch validity
    if: github.repository != 'EpitechPGEPromo2029/B-DOP-200-LIL-2-1-chocolatine-arthur.vignes'
    runs-on: ubuntu-latest
    outputs:
      branch_valid: ${{ !startsWith(github.ref, 'refs/heads/ga-ignore-') }}
    steps:
      - name: Verify branch
        id: branch_check
        run: |
          if [[ "${{ github.ref }}" == refs/heads/ga-ignore-* ]]; then
            echo "Branch is ignored (ga-ignore-*)"
            echo "branch_valid=false" >> $GITHUB_OUTPUT
          else
            echo "Branch is valid"
            echo "branch_valid=true" >> $GITHUB_OUTPUT
          fi

  check_coding_style:
    name: coding style checker
    if: github.repository != 'EpitechPGEPromo2029/B-DOP-200-LIL-2-1-chocolatine-arthur.vignes'
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    outputs:
      run_rest_jobs: ${{ steps.set_output.outputs.run_jobs }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: run coding style
        run: check.sh $(pwd) $(pwd)

      - name: check style error
        id: set_output
        run: |
          if [ -s $(pwd)/coding-style-reports.log ]; then
            echo "run_jobs=false" >> $GITHUB_OUTPUT
            while IFS=':' read -r FILE LINE GRAVITY ERROR; do
              echo "::error file=$FILE,line=$LINE,title=$GRAVITY::$ERROR"
            done < $(pwd)/coding-style-reports.log
          else
            echo "run_jobs=true" >> $GITHUB_OUTPUT
          fi

  check_compilation:
    name: Checking compilation
    if: github.repository != 'EpitechPGEPromo2029/B-DOP-200-LIL-2-1-chocolatine-arthur.vignes'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    outputs:
      run_rest_jobs: ${{ steps.set_output.outputs.run_jobs }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: run make
        timeout-minutes: 2
        run: make

      - name: check files existence
        id: set_output
        run: |
          if [ -f "${{ env.EXECUTABLES }}" ]; then
            echo "run_jobs=true" >> $GITHUB_OUTPUT
          else
            echo "run_jobs=false" >> $GITHUB_OUTPUT
            echo "::error:: compilation failed"
          fi

  push_to_mirror:
    name: mirror repository
    needs: [check_compilation, check_coding_style]
    if: needs.check_compilation.outputs.run_rest_jobs == 'true' && needs.check_coding_style.outputs.run_rest_jobs == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
